"""add events table

Revision ID: f35c181fe48e
Revises: 815fc57bf0da
Create Date: 2022-10-09 21:42:55.554538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f35c181fe48e'
down_revision = '815fc57bf0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'stream_events',
        sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('name', sa.Text(), nullable=True),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=True, index=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_stream_events'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_events')
    # ### end Alembic commands ###
