version: '3.7'
services:
  auth_service: &main
    restart: "no"
    build:
      context: .

      args:
        MAX_WORKERS: ${AUTH_SERVICE_MAX_WORKERS}


    ports:
      - ${AUTH_SERVICE_PORT}:8000

    env_file:
      - .env


    volumes:
      - ${AUTH_SERVICE_FILES_PATH_VOLUME}:/var/file_storage

    environment:
      - AUTH_SERVICE_FILES_DIR=/var/file_storage
    networks:
      - local_net


  postgres_auth:
    restart: "on-failure"
    image: "postgres:13-alpine"

    environment:
      - POSTGRES_USER=${AUTH_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_SERVICE_DB_NAME}

    ports:
      - ${AUTH_SERVICE_DB_PORT}:5432

    volumes:
      - ${AUTH_SERVICE_POSTGRES_DATA_VOLUME}:/var/lib/postgresql/data

    networks:
      - local_net

  # я слишком ленив чтобы разносить базы в 1 инстансе
  postgres_tracker:
    restart: "on-failure"
    image: "postgres:13-alpine"

    environment:
      - POSTGRES_USER=${TRACKER_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${TRACKER_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${TRACKER_SERVICE_DB_NAME}

    ports:
      - ${TRACKER_SERVICE_DB_PORT}:5432

    volumes:
      - ${TRACKER_SERVICE_POSTGRES_DATA_VOLUME}:/var/lib/postgresql/data

    networks:
      - local_net

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - ${KAFKA_VOLUME}:/bitnami

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "9192:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

networks:
  local_net:
