"""add extra price field

Revision ID: 647ae1301c89
Revises: ab84b3dd435d
Create Date: 2022-10-10 01:11:27.701588

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '647ae1301c89'
down_revision = 'ab84b3dd435d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assign_price', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('complete_price', sa.Integer(), nullable=False))
    op.drop_column('tasks', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'complete_price')
    op.drop_column('tasks', 'assign_price')
    # ### end Alembic commands ###
