"""init migration

Revision ID: 35a06d5ad0ed
Revises:
Create Date: 2022-10-10 00:08:11.286287

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35a06d5ad0ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'statuses',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_statuses'))
    )
    op.create_table(
        'stream_events',
        sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('name', sa.Text(), nullable=True),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_stream_events'))
    )
    op.create_table(
        'users',
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.Column('login', sa.String(length=64), nullable=True),
        sa.Column('email', sa.String(length=256), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.Column('role_name', sa.Text(), nullable=True),
        sa.Column('first_name', sa.String(length=256), nullable=True),
        sa.Column('last_name', sa.String(length=256), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table(
        'tasks',
        sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('name', sa.String(length=512), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status_id', sa.Integer(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('assigned_by', postgresql.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_tasks_assigned_by_users')),
        sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_tasks_status_id_statuses')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_table(
        'status_changes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('status_id', sa.Integer(), nullable=False),
        sa.Column('task_id', postgresql.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['status_id'],
            ['statuses.id'],
            name=op.f('fk_status_changes_status_id_statuses')
        ),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_status_changes_task_id_tasks')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_status_changes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_changes')
    op.drop_table('tasks')
    op.drop_table('users')
    op.drop_table('stream_events')
    op.drop_table('statuses')
    # ### end Alembic commands ###
