"""prices are nullable

Revision ID: 4874bea20823
Revises: 647ae1301c89
Create Date: 2022-10-10 02:27:33.252082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4874bea20823'
down_revision = '647ae1301c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'assign_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'complete_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'complete_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'assign_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
